version: 2.1
orbs: # packages
  docker: circleci/docker@2.1.4 # allows us to use docker orb's commands
  snyk: snyk/snyk@1.5.0 # 3rd party orb of snyk
  # heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Test
          command: |
            mvn test -Dtest="ExpenseControllerTest#createExpenseTest"
            mvn test -Dtest="ExpenseControllerTest#createExpenseWithWalletNotFoundExceptionTest"
            mvn test -Dtest="ExpenseControllerTest#invalidCreateExpenseTest"
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: clumped/project-space
      - docker/push:
          image: clumped/project-space
  scan:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      IMAGE_NAME: clumped/project-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan: 
          docker-image-name: $IMAGE_NAME
  deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - setup_remote_docker
      - heroku/install #installs heroku cli for our run command
      - checkout
      - run:
          name: Heroku Container Push # the name of the group of commands we are running
          command: |
            heroku container:login
            heroku container:push web -a m3-proj-expenses-tracker-test # Need to change once confirm to deploy
            heroku container:release web -a m3-proj-expenses-tracker-test # Need to change once confirm to deploy
        # The push command pushes the image to heroku's container registry
        # The release command deploys the image from heroku's container registry

workflows:
  ci-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop2
      - test:
          requires:
            - build
      - scan:
          requires:
            - build
      - build-and-push:
          requires:
            - test

  cicd-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - scan:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - build-and-push
